spring:
  application:
    name: spring-jwt-auth
  output:
    ansi:
      enabled: always

server:
  port: 8080

jwt:
  expiration: 86400  # 24 hours in seconds

management:
  endpoints:
    web:
      exposure:
        include: ["health", "metrics", "info", "prometheus"]
      base-path: /actuator
      cors:
        allowed-origins: "*"
        allowed-methods: GET
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{REQUEST_ID},%X{USER_ID}]"
  level:
    root: INFO
    com.example: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO