apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-jwt
  namespace: staging
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-jwt
  template:
    metadata:
      labels:
        app: spring-boot-jwt
    spec:
      containers:
      - name: practice-container
        image: louishu/practice:1.0
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "staging"
        resources:
          requests:
            cpu: "100m"    
            memory: "128Mi" 
          limits:
            cpu: "200m"    
            memory: "256Mi" 
      imagePullSecrets:
      - name: regcred01
