apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

bases:
- ../../base

images:
- name: louishu/practice
  newTag: 1.1

patchesStrategicMerge:
- patches/deployment-patch.yaml

resources:
- namespace.yaml
