apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

bases:
- ../../base

images:
- name: louishu/practice
  newTag: 33ce866

patchesStrategicMerge:
- patches/deployment-patch.yaml

resources:
- namespace.yaml

commonLabels:
  app.kubernetes.io/name: spring-boot-jwt
  app.kubernetes.io/part-of: auth-service
