apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-jwt
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring-boot-jwt
  template:
    metadata:
      labels:
        app: spring-boot-jwt
    spec:
      containers:
      - name: practice-container
        image: louishu/practice:1.0
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "production"
        resources:
          requests:
            cpu: "100m"    
            memory: "128Mi" 
          limits:
            cpu: "200m"    
            memory: "256Mi" 
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 15
      imagePullSecrets:
      - name: regcred01
