apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-jwt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-jwt
  template:
    metadata:
      labels:
        app: spring-boot-jwt
    spec:
      containers:
      - name: spring-boot-jwt
        image: louishu/practice:1.0  # This will be overridden in overlays
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
